const REQUEST_CHANEL_DATA = 'REQUEST_CHANEL_DATA';
const GET_CHANEL_DATA = 'GET_CHANEL_DATA';
const REQUEST_LISTS = 'REQUEST_LISTS';
const GET_LISTS = 'GET_LISTS';
const REQUEST_VIDEOS = 'REQUEST_VIDEOS';
const GET_VIDEOS = 'GET_VIDEOS';
const REQUEST_VIDEO_DATA = 'REQUEST_VIDEO_DATA';
const GET_VIDEO_DATA = 'GET_VIDEO_DATA';
const REQUEST_ERROR = 'REQUEST_ERROR';

export {REQUEST_CHANEL_DATA, GET_CHANEL_DATA, REQUEST_LISTS, GET_LISTS, REQUEST_VIDEOS, GET_VIDEOS, REQUEST_VIDEO_DATA, GET_VIDEO_DATA, REQUEST_ERROR};